# Generated by Django 4.0.5 on 2022-07-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('auteur', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=250)),
                ('date_parution', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
