# Generated by Django 4.0.5 on 2022-07-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.categorie'),
        ),
    ]
