# Generated by Django 4.0.5 on 2022-07-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recette_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('unit', models.CharField(max_length=2)),
                ('recette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.recette')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('contenu', models.CharField(max_length=1000)),
                ('note', models.IntegerField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('recette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.recette')),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.member'),
        ),
    ]
